config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :profiles do
  member do
    get "vote"
  end
end

  resources :programs

  resources :locations

  resources :organizations do
  member do
    get "vote"
  end
end

  resources :class_sessions do
  member do
    get "vote"
  end
end

  resources :grades

  resources :guest_educators do
  member do
    get "vote"
  end
end

  resources :announcements do
  member do
    get "vote"
  end
end

  resources :training_records do
  member do
    get "vote"
  end
end

  resources :trainings do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  acts_as_votable 
end

app/models/class_session.rb
class ClassSession < ActiveRecord::Base
  has_one :program
  has_one :organization
  has_many :profiles
  has_many :grades
  has_one :guest_educator
  acts_as_votable 
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :class_session
end

app/models/grades.rb
class Grades < ActiveRecord::Base
  belongs_to :class_session
end

app/models/guest_educator.rb
class GuestEducator < ActiveRecord::Base
  belongs_to :class_session
  acts_as_votable 
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :organization
  belongs_to :profile
  belongs_to :training
  validates_formatting_of :zipcode, using: :us_zip
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :class_session
  has_and_belongs_to_many :organizations
  has_many :locations
  has_many :profiles
  acts_as_votable 
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  belongs_to :organization
  belongs_to :class_session
  has_many :programs
  has_one :location
  acts_as_votable 
end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :profile
  belongs_to :class_session
  belongs_to :training_record
  belongs_to :training
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_one :program
  has_one :location
  has_many :training_records
  acts_as_votable 
end

app/models/training_record.rb
class TrainingRecord < ActiveRecord::Base
  belongs_to :profile
  belongs_to :training
  has_one :program
  acts_as_votable 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  belongs_to :profile
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
  acts_as_votable 
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy, :vote]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @announcement.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:name, :message, :display_until)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :message, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :message, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :display_until, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :display_until, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  announcements_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Announcement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/announcements/index.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Announcement %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= model_class.human_attribute_name(:display_until) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.id %></td>
        <td><%= announcement.name %></td>
        <td><%= announcement.message %></td>
        <td><%= announcement.display_until %></td>
        <td><%=l announcement.created_at, format: :long %></td>
        <td>
          <%= link_to announcement_path(announcement), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to announcement_path(announcement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_announcement_path,
            :class => 'btn btn-primary' %>

app/views/announcements/new.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Announcement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/announcements/show.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Announcement %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @announcement.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:message) %></dt>
      <dd><pre class="prettyprint"><%= @announcement.message %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:display_until) %></dt>
      <dd><pre class="prettyprint"><%= @announcement.display_until %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              announcements_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_announcement_path(@announcement), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              announcement_path(@announcement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>